### PR TITLE
RHCIQE  569

### PR DESCRIPTION
**Pull request by jamesooden**
Adds test to test if the filter capability of the deployments page works.   I will in a different merge add the cleanup code (i.e. RHCIQE-573)

### CODE REVIEW

**Comment by LandoCalrizzian** [comment]
We shouldn't have internal links in a public repo

**Comment by apagac** [comment]
👍

**Comment by jamesooden** [comment]
Removed the internal link from the comment

**Comment by LandoCalrizzian** [comment]
+1
Offline discussion about neccessity of polarion testcase references won't block merge for this PR

**Comment by jamesooden** [comment]
And here is the discussion:

02:57:35 PM) oden: Hey Landon is there anything else I need to do with this:  https://github.com/RedHatQE/fusor-qe/pull/87#issuecomment-286880794
(03:02:23 PM) landon: not that I can see. the only minor issue is that it has references to polarion testcase numbers
(03:02:38 PM) oden: We don't even want the numbers in there?
(03:03:26 PM) oden: That's going to make it really hard for us to know what tests maps to which Polarion test.
(03:03:56 PM) landon: i think this came up back in november. since polarion testcases can change that polarion should reference the script but fusor-qe don't reference polarion
(03:04:23 PM) oden: I guarantee you there will be times when we want to go backwards.
(03:04:37 PM) landon: it's a public repo that can be used by anyone so it doesn't need to be in fusor-qe.
(03:04:57 PM) landon: there are internal things we can do to map fusor-qe to polarion
(03:06:14 PM) oden: I mean we have the field in the polarion tests but I don't know how easy it is to search by that and get the Polartion test from the fuser-qe test.
(03:06:17 PM) landon: what happens if we redo all the polarion testcase #'s for qci 1.2, do we rename the testcase if it still works for qci 1.2?
(03:06:54 PM) oden: Yes, that is what we would have to do.    Is there a high likelyhood of that?
(03:07:28 PM) oden: I get what your saying, but I think the principle applied too strictly will make our life more difficult
(03:07:47 PM) landon: it's always a possibility. I don't think that every update in polarion should require a fusor-qe PR
(03:14:16 PM) oden: It would only be name changes, but I see your point.   Right now all the tests, of which there are not many have these references.   I personally find them very helpful.
(03:18:23 PM) landon: I see the value of having the link to polarion but in my opinion it should be in an internal repo and not fusor-qe.
(03:19:09 PM) oden: Or just a spreadsheet even
(03:19:25 PM) landon: I think fusor-ci would be a better fit for what you're suggesting. we can easily host those pytests in fusor-ci with the polarion link
(03:19:29 PM) oden: But if its easy to search by the automation script in polartion then it shouldn't bad.
(03:19:59 PM) oden: I really don't want to move those tests in fusor-ci.   
(03:20:29 PM) oden: Also, there is very little in fusor-ci that really needs to be in an internal repo.
(03:20:38 PM) oden: just the password stuff really
(03:20:48 PM) landon: the test wouldn't move. you just have fusor-ci/tests/test_polarion_qci123.py that is a wrapper for fusor-qe/test/test_foo.py
(03:20:56 PM) oden: Oh
(03:21:56 PM) landon: that would allow any qci customer to use fusor-qe without the poloarion info but we can have fusor-ci with full polarion info
(03:22:58 PM) oden: So let me remove the references in the code I changed, and I create separate PR to remove it from the older tests
(03:23:02 PM) oden: I'll
(03:23:42 PM) landon: I wouldn't worry about removing it right now. from the info so far in the qci planning meeting everything is about to change
(03:23:55 PM) oden: I hear
(03:24:01 PM) oden: am hearing it
(03:24:11 PM) oden: So do I need to change anything for the current PR?
(03:42:25 PM) landon: I +1'd with a comment about our chat

**Pull request merged**
