### PR TITLE
Adding directory structure for wizard pages and blank files for each page

### PR DESCRIPTION
**Pull request by blrm**
This defines the file structure for where each of the pages should be located. I also relocated wizard.py to be under the wizard directory and renamed it product_selection.py. The rest of the pages live under the directory of their respective products.

### CODE REVIEW

**Comment by apagac** [comment]
lgtm

**Comment by jamesooden** [comment]
lgtm

**Comment by blrm** [comment]
lgtm

**Comment by blrm** [comment]
lgtm.co is lagging or broken, I'm merging this PR and disabling the lgtm plugin

**Pull request merged**
