### PR TITLE
Bring in base base class from robottelo

### PR DESCRIPTION
**Pull request by jamesooden**
But strip it down to just what we use.

https://projects.engineering.redhat.com/browse/RHCIQE-6

### CODE REVIEW

**Comment by blrm** [comment]
This looks good to me, thanks for getting this out of robottelo and cleaning it up.

**Comment by omaciel** [comment]
Great to see code being re-used 💯

**Comment by blrm** [comment]
@omaciel Thanks for producing such great stuff! I think we will be using nailgun soon as well.

**Comment by omaciel** [comment]
@blrm 💃

**Pull request merged**
